# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Suds' do
  pod 'Stripe', '~> 14.0.0'
  # Pods for Suds
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Required by RNFirebase
  # [OPTIONAL PODS] - comment out pods for firebase products you won't be using.
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Functions'
  pod 'Firebase/Firestore'
  pod 'Firebase/Messaging'
  pod 'Firebase/Storage'
  pod 'Firebase/Performance'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/RemoteConfig'
  # pod 'Firebase/AdMob', '~> 5.20.1'
  # pod 'Firebase/Invites', '~> 5.20.1'
  pod 'Fabric', '~> 1.9.0'
  pod 'Crashlytics', '~> 3.12.0'

  # pod 'React', :path => '../node_modules/react-native'
  # pod 'React', :path => '../node_modules/react-native', subspecs: [
  #   'Core',
  #   'CxxBridge',
  #   'DevSupport',
  #   'RCTActionSheet',
  #   'RCTAnimation',
  #   'RCTGeolocation',
  #   'RCTImage',
  #   'RCTLinkingIOS',
  #   'RCTNetwork',
  #   'RCTSettings',
  #   'RCTText',
  #   'RCTVibration',
  #   'RCTWebSocket',
  # ]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  # pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
  # pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  # pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'
  # pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'
  # pod 'react-native-pdf', :path => '../node_modules/react-native-pdf'


  # pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  # pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

end

target 'Suds-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Suds-tvOS

  target 'Suds-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end